/* _GlobalPrefix_ */
"use strict";this.default_host=this.default_host||{};(function(_){var window=this;
/* _Module_:ultraviolet_base_module */
try{
_.aa=_.aa||{};_.k=this;_.ca="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
/* _Module_:sy0 */
try{
var da,ea;_.p=function(a){return void 0!==a};da=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};ea=function(a,b,c){return a.call.apply(a.bind,arguments)};
_.fa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.r=function(a,b){function c(){}c.prototype=b.prototype;a.A=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Rc=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
_.ga=function(a,b){a=a.split(".");var c=_.k;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&_.p(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}};_.ha=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.t=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?_.t=ea:_.t=da;return _.t.apply(null,arguments)};
_.ia=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.ja=function(a){return"function"==_.fa(a)};_.ka=function(a){return"number"==typeof a};_.u=function(a){return"string"==typeof a};_.la=function(a){var b=_.fa(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.w=function(a){return"array"==_.fa(a)};_.ma=function(){};_.na=function(a){a=a.split(".");for(var b=_.k,c;c=a.shift();)if(null!=b[c])b=b[c];else return null;return b};
_.oa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.oa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.r(_.oa,Error);_.oa.prototype.name="CustomError";var pa;var wa,xa,ya,za,Aa,Ba,va,Da,Fa;_.ra=function(a,b){return 0==a.lastIndexOf(b,0)};_.sa=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};_.ta=function(a){return/^[\s\xa0]*$/.test(a)};_.ua=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
_.Ca=function(a){if(!va.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(wa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(xa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ya,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(za,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Aa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ba,"&#0;"));return a};wa=/&/g;xa=/</g;ya=/>/g;za=/"/g;Aa=/'/g;Ba=/\x00/g;va=/[\x00&<>"']/;Da=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
_.Ea=function(a){return null==a?"":String(a)};
_.Ga=function(a,b){var c=0;a=(0,_.ua)(String(a)).split(".");b=(0,_.ua)(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",h=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==f[0].length&&0==h[0].length)break;c=Fa(0==f[1].length?0:(0,window.parseInt)(f[1],10),0==h[1].length?0:(0,window.parseInt)(h[1],10))||Fa(0==f[2].length,0==h[2].length)||Fa(f[2],h[2]);f=f[3];h=h[3]}while(0==c)}return c}; Fa=function(a,b){return a<b?-1:a>b?1:0};
var Ha;Ha=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.u(a))return _.u(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.x=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.u(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.Ia=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=_.u(a)?a.split(""):a,l=0;l<d;l++)if(l in h){var n=h[l];b.call(c,n,l,a)&&(e[f++]=n)}return e};_.Ja=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.u(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};
_.Ka=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.u(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.Ma=function(a,b){b=_.La(a,b,void 0);return 0>b?null:_.u(a)?a.charAt(b):a[b]};_.La=function(a,b,c){for(var d=a.length,e=_.u(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};_.Na=function(a,b){return 0<=Ha(a,b)};_.Pa=function(a,b){b=Ha(a,b);var c;(c=0<=b)&&_.Oa(a,b);return c}; _.Oa=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};_.Qa=function(a){return Array.prototype.concat.apply([],arguments)};_.Ra=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
a:{var Ta=_.k.navigator;if(Ta){var Ua=Ta.userAgent;if(Ua){_.Sa=Ua;break a}}_.Sa=""}_.y=function(a){return-1!=_.Sa.indexOf(a)};var Wa,Xa,Ya,$a;_.Va=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Wa=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};Xa=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};Ya=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};_.Za=function(a){var b={},c;for(c in a)b[c]=a[c];return b};$a="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "); _.ab=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<$a.length;f++)c=$a[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var bb=function(){return(_.y("Chrome")||_.y("CriOS"))&&!_.y("Edge")};var cb,db;cb=function(){return _.y("iPhone")&&!_.y("iPod")&&!_.y("iPad")};db=function(){return cb()||_.y("iPad")||_.y("iPod")};_.eb=function(){return _.y("Macintosh")};_.fb=function(){return _.y("Windows")};_.gb=function(){return _.y("CrOS")};var hb=function(a){hb[" "](a);return a};hb[" "]=_.ma;_.ib=function(a,b){try{return hb(a[b]),!0}catch(c){}return!1};_.jb=function(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)};var kb,lb,ob,sb,tb,xb,yb,Ab;kb=_.y("Opera");_.z=_.y("Trident")||_.y("MSIE");lb=_.y("Edge");_.mb=_.y("Gecko")&&!(-1!=_.Sa.toLowerCase().indexOf("webkit")&&!_.y("Edge"))&&!(_.y("Trident")||_.y("MSIE"))&&!_.y("Edge");_.nb=-1!=_.Sa.toLowerCase().indexOf("webkit")&&!_.y("Edge");ob=_.k.navigator||null;_.pb=ob&&ob.platform||"";_.qb=_.eb();_.rb=_.fb();sb=function(){var a=_.k.document;return a?a.documentMode:void 0};
a:{var ub="",vb=function(){var a=_.Sa;if(_.mb)return/rv\:([^\);]+)(\)|;)/.exec(a);if(lb)return/Edge\/([\d\.]+)/.exec(a);if(_.z)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.nb)return/WebKit\/(\S+)/.exec(a);if(kb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();vb&&(ub=vb?vb[1]:"");if(_.z){var wb=sb();if(null!=wb&&wb>(0,window.parseFloat)(ub)){tb=String(wb);break a}}tb=ub}xb=tb;yb={};_.zb=function(a){return _.jb(yb,a,function(){return 0<=_.Ga(xb,a)})};var Bb=_.k.document; Ab=Bb&&_.z?sb()||("CSS1Compat"==Bb.compatMode?(0,window.parseInt)(xb,10):5):void 0;
var Cb=_.y("Firefox"),Db=cb()||_.y("iPod"),Eb=_.y("iPad"),Fb=_.y("Android")&&!(bb()||_.y("Firefox")||_.y("Opera")||_.y("Silk")),Gb=bb(),Hb=_.y("Safari")&&!(bb()||_.y("Coast")||_.y("Opera")||_.y("Edge")||_.y("Silk")||_.y("Android"))&&!db();var Ib=null;var Jb,Kb,Mb,Lb,Pb,Qb,Ob;Jb=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))};Kb=function(a){a=String(a);if(Jb(a))try{return eval("("+a+")")}catch(b){}throw Error("c`"+a);};_.Nb=function(a){var b=[];Lb(new Mb,a,b);return b.join("")};Mb=function(){};
Lb=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(_.w(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),Lb(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),Ob(d,c),c.push(":"),Lb(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":Ob(b,c);break;case "number":c.push((0,window.isFinite)(b)&&
!(0,window.isNaN)(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("d`"+typeof b);}}};Pb={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};Qb=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;Ob=function(a,b){b.push('"',a.replace(Qb,function(a){var b=Pb[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),Pb[a]=b);return b}),'"')};
var Tb,Vb,Yb;_.A=function(){};_.Rb="function"==typeof window.Uint8Array;_.B=function(a,b,c,d,e){a.b=null;b||(b=c?[c]:[]);a.o=c?String(c):void 0;a.h=0===c?-1:0;a.g=b;a:{if(a.g.length&&(b=a.g.length-1,(c=a.g[b])&&"object"==typeof c&&!_.w(c)&&!(_.Rb&&c instanceof window.Uint8Array))){a.D=b-a.h;a.c=c;break a}a.D=Number.MAX_VALUE}a.m={};if(d)for(b=0;b<d.length;b++)c=d[b],c<a.D?(c+=a.h,a.g[c]=a.g[c]||_.Sb):a.c[c]=a.c[c]||_.Sb;e&&e.length&&(0,_.x)(e,_.ha(Tb,a))};_.Sb=[];
_.C=function(a,b){if(b<a.D){b+=a.h;var c=a.g[b];return c===_.Sb?a.g[b]=[]:c}c=a.c[b];return c===_.Sb?a.c[b]=[]:c};_.Ub=function(a,b,c){a=_.C(a,b);return null==a?c:a};_.D=function(a,b,c){b<a.D?a.g[b+a.h]=c:a.c[b]=c};Tb=function(a,b){var c,d;(0,_.x)(b,function(b){var e=_.C(a,b);null!=e&&(c=b,d=e,_.D(a,b,void 0))});return c?(_.D(a,c,d),c):0};_.E=function(a,b,c){a.b||(a.b={});if(!a.b[c]){var d=_.C(a,c);d&&(a.b[c]=new b(d))}return a.b[c]};
_.G=function(a,b,c){a.b||(a.b={});var d=c?_.F(c):c;a.b[b]=c;_.D(a,b,d)};Vb=function(a){if(a.b)for(var b in a.b){var c=a.b[b];if(_.w(c))for(var d=0;d<c.length;d++)c[d]&&_.F(c[d]);else c&&_.F(c)}};_.F=function(a){Vb(a);return a.g};
_.A.prototype.j=_.Rb?function(){var a=window.Uint8Array.prototype.toJSON;window.Uint8Array.prototype.toJSON=function(){if(!Ib){Ib={};for(var a=0;65>a;a++)Ib[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)}for(var a=Ib,b=[],e=0;e<this.length;e+=3){var f=this[e],h=e+1<this.length,l=h?this[e+1]:0,n=e+2<this.length,q=n?this[e+2]:0,v=f>>2,f=(f&3)<<4|l>>4,l=(l&15)<<2|q>>6,q=q&63;n||(q=64,h||(l=64));b.push(a[v],a[f],a[l],a[q])}return b.join("")};try{var b=JSON.stringify(_.F(this),
Wb)}finally{window.Uint8Array.prototype.toJSON=a}return b}:function(){return JSON.stringify(_.F(this),Wb)};var Wb=function(a,b){if(_.ka(b)){if((0,window.isNaN)(b))return"NaN";if(window.Infinity===b)return"Infinity";if(-window.Infinity===b)return"-Infinity"}return b};_.A.prototype.toString=function(){Vb(this);return this.g.toString()};Yb=function(a,b){a=a||{};b=b||{};var c={},d;for(d in a)c[d]=0;for(d in b)c[d]=0;for(d in c)if(!_.Xb(a[d],b[d]))return!1;return!0};
_.Xb=function(a,b){if(a==b)return!0;if(!_.ia(a)||!_.ia(b)||a.constructor!=b.constructor)return!1;if(_.Rb&&a.constructor===window.Uint8Array){if(a.length!=b.length)return!1;for(var c=0;c<a.length;c++)if(a[c]!=b[c])return!1;return!0}if(a.constructor===Array){for(var d=void 0,e=void 0,f=Math.max(a.length,b.length),c=0;c<f;c++){var h=a[c],l=b[c];h&&h.constructor==Object&&(d=h,h=void 0);l&&l.constructor==Object&&(e=l,l=void 0);if(!_.Xb(h,l))return!1}return d||e?(d=d||{},e=e||{},Yb(d,e)):!0}if(a.constructor=== Object)return Yb(a,b);throw Error("e");};
_.H=function(){this.G=this.G;this.D=this.D};_.H.prototype.G=!1;_.H.prototype.$=function(){this.G||(this.G=!0,this.v())};_.K=function(a,b){_.I(a,_.ha(_.J,b))};_.I=function(a,b,c){a.G?_.p(c)?b.call(c):b():(a.D||(a.D=[]),a.D.push(_.p(c)?(0,_.t)(b,c):b))};_.H.prototype.v=function(){if(this.D)for(;this.D.length;)this.D.shift()()};_.J=function(a){a&&"function"==typeof a.$&&a.$()};
_.Zb=function(a){return function(){return a}}(!1);var $b="StopIteration"in _.k?_.k.StopIteration:{message:"StopIteration",stack:""},ac=function(){};ac.prototype.next=function(){throw $b;};ac.prototype.ha=function(){return this};
var bc=function(a){if(a instanceof ac)return a;if("function"==typeof a.ha)return a.ha(!1);if(_.la(a)){var b=0,c=new ac;c.next=function(){for(;;){if(b>=a.length)throw $b;if(b in a)return a[b++];b++}};return c}throw Error("f");},cc=function(a,b){if(_.la(a))try{(0,_.x)(a,b,void 0)}catch(c){if(c!==$b)throw c;}else{a=bc(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==$b)throw c;}}},dc=function(a){if(_.la(a))return _.Ra(a);a=bc(a);var b=[];cc(a,function(a){b.push(a)});return b};
_.L=function(a,b){this.b={};this.a=[];this.c=this.g=0;var c=arguments.length;if(1<c){if(c%2)throw Error("b");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.L?(c=a.W(),d=a.R()):(c=Ya(a),d=Xa(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.L.prototype.R=function(){ec(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.L.prototype.W=function(){ec(this);return this.a.concat()};_.gc=function(a,b){return fc(a.b,b)};
_.L.prototype.clear=function(){this.b={};this.c=this.g=this.a.length=0};_.L.prototype.remove=function(a){return fc(this.b,a)?(delete this.b[a],this.g--,this.c++,this.a.length>2*this.g&&ec(this),!0):!1};var ec=function(a){var b,c;if(a.g!=a.a.length){for(b=c=0;c<a.a.length;){var d=a.a[c];fc(a.b,d)&&(a.a[b++]=d);c++}a.a.length=b}if(a.g!=a.a.length){var e={};for(b=c=0;c<a.a.length;)d=a.a[c],fc(e,d)||(a.a[b++]=d,e[d]=1),c++;a.a.length=b}};_.L.prototype.get=function(a,b){return fc(this.b,a)?this.b[a]:b};
_.L.prototype.set=function(a,b){fc(this.b,a)||(this.g++,this.a.push(a),this.c++);this.b[a]=b};_.L.prototype.forEach=function(a,b){for(var c=this.W(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.L.prototype.ha=function(a){ec(this);var b=0,c=this.c,d=this,e=new ac;e.next=function(){if(c!=d.c)throw Error("g");if(b>=d.a.length)throw $b;var e=d.a[b++];return a?e:d.b[e]};return e};var fc=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.hc=function(a){if(a.R&&"function"==typeof a.R)return a.R();if(_.u(a))return a.split("");if(_.la(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Xa(a)};
_.ic=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(_.la(a)||_.u(a))(0,_.x)(a,b,void 0);else{if(a.W&&"function"==typeof a.W)var c=a.W();else if(a.R&&"function"==typeof a.R)c=void 0;else if(_.la(a)||_.u(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=Ya(a);for(var d=_.hc(a),e=d.length,f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};
var jc=function(a,b,c){this.c=c;this.g=a;this.h=b;this.b=0;this.a=null};jc.prototype.get=function(){if(0<this.b){this.b--;var a=this.a;this.a=a.next;a.next=null}else a=this.g();return a};var kc=function(a,b){a.h(b);a.b<a.c&&(a.b++,b.next=a.a,a.a=b)};var oc;_.lc=[];_.mc=[];_.nc=!1;oc=function(a){_.lc[_.lc.length]=a;if(_.nc)for(var b=0;b<_.mc.length;b++)a((0,_.t)(_.mc[b].b,_.mc[b]))};var pc,rc,sc,qc;pc=function(a){_.k.setTimeout(function(){throw a;},0)};_.tc=function(a,b){var c=a;b&&(c=(0,_.t)(a,b));c=qc(c);!_.ja(_.k.setImmediate)||_.k.Window&&_.k.Window.prototype&&!_.y("Edge")&&_.k.Window.prototype.setImmediate==_.k.setImmediate?(rc||(rc=sc()),rc(c)):_.k.setImmediate(c)};
sc=function(){var a=_.k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.y("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.t)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.y("Trident")&&!_.y("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.p(c.next)){c=c.next;var a=c.vb;c.vb=null;a()}};return function(a){d.next={vb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=
window.document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.k.setTimeout(a,0)}};qc=function(a){return a};oc(function(a){qc=a});
var uc=function(){this.b=this.a=null},wc=new jc(function(){return new vc},function(a){a.reset()},100);uc.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var vc=function(){this.next=this.b=this.a=null};vc.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};vc.prototype.reset=function(){this.next=this.b=this.a=null};
var Bc=function(a,b){xc||yc();zc||(xc(),zc=!0);var c=Ac,d=wc.get();d.set(a,b);c.b?c.b.next=d:c.a=d;c.b=d},xc,yc=function(){if(-1!=String(_.k.Promise).indexOf("[native code]")){var a=_.k.Promise.resolve(void 0);xc=function(){a.then(Cc)}}else xc=function(){_.tc(Cc)}},zc=!1,Ac=new uc,Cc=function(){for(var a;a=Ac.remove();){try{a.a.call(a.b)}catch(b){pc(b)}kc(wc,a)}zc=!1};
var Dc=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},Ec=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var Hc,Ic,Jc,Oc,Sc,Tc,Rc,Pc;_.Gc=function(a,b){this.a=0;this.D=void 0;this.c=this.b=this.g=null;this.h=this.j=!1;if(a!=_.ma)try{var c=this;a.call(b,function(a){_.Fc(c,2,a)},function(a){_.Fc(c,3,a)})}catch(d){_.Fc(this,3,d)}};Hc=function(){this.next=this.c=this.b=this.h=this.a=null;this.g=!1};Hc.prototype.reset=function(){this.c=this.b=this.h=this.a=null;this.g=!1};Ic=new jc(function(){return new Hc},function(a){a.reset()},100);Jc=function(a,b,c){var d=Ic.get();d.h=a;d.b=b;d.c=c;return d};
_.Lc=function(){var a,b=new _.Gc(function(b){a=b});return new Kc(b,a)};_.Gc.prototype.then=function(a,b,c){return _.Mc(this,_.ja(a)?a:null,_.ja(b)?b:null,c)};Dc(_.Gc);_.Gc.prototype.cancel=function(a){0==this.a&&Bc(function(){var b=new Nc(a);Oc(this,b)},this)};
Oc=function(a,b){if(0==a.a)if(a.g){var c=a.g;if(c.b){for(var d=0,e=null,f=null,h=c.b;h&&(h.g||(d++,h.a==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.a&&1==d?Oc(c,b):(f?(d=f,d.next==c.c&&(c.c=d),d.next=d.next.next):Pc(c),Qc(c,e,3,b)))}a.g=null}else _.Fc(a,3,b)};Sc=function(a,b){a.b||2!=a.a&&3!=a.a||Rc(a);a.c?a.c.next=b:a.b=b;a.c=b};
_.Mc=function(a,b,c,d){var e=Jc(null,null,null);e.a=new _.Gc(function(a,h){e.h=b?function(c){try{var e=b.call(d,c);a(e)}catch(q){h(q)}}:a;e.b=c?function(b){try{var e=c.call(d,b);!_.p(e)&&b instanceof Nc?h(b):a(e)}catch(q){h(q)}}:h});e.a.g=a;Sc(a,e);return e.a};_.Gc.prototype.m=function(a){this.a=0;_.Fc(this,2,a)};_.Gc.prototype.o=function(a){this.a=0;_.Fc(this,3,a)};
_.Fc=function(a,b,c){if(0==a.a){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.a=1;a:{var d=c,e=a.m,f=a.o;if(d instanceof _.Gc){Sc(d,Jc(e||_.ma,f||null,a));var h=!0}else if(Ec(d))d.then(e,f,a),h=!0;else{if(_.ia(d))try{var l=d.then;if(_.ja(l)){Tc(d,l,e,f,a);h=!0;break a}}catch(n){f.call(a,n);h=!0;break a}h=!1}}h||(a.D=c,a.a=b,a.g=null,Rc(a),3!=b||c instanceof Nc||Uc(a,c))}};
Tc=function(a,b,c,d,e){var f=!1,h=function(a){f||(f=!0,c.call(e,a))},l=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,h,l)}catch(n){l(n)}};Rc=function(a){a.j||(a.j=!0,Bc(a.l,a))};Pc=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.c=null);return b};_.Gc.prototype.l=function(){for(var a;a=Pc(this);)Qc(this,a,this.a,this.D);this.j=!1};
var Qc=function(a,b,c,d){if(3==c&&b.b&&!b.g)for(;a&&a.h;a=a.g)a.h=!1;if(b.a)b.a.g=null,Vc(b,c,d);else try{b.g?b.h.call(b.c):Vc(b,c,d)}catch(e){Wc.call(null,e)}kc(Ic,b)},Vc=function(a,b,c){2==b?a.h.call(a.c,c):a.b&&a.b.call(a.c,c)},Uc=function(a,b){a.h=!0;Bc(function(){a.h&&Wc.call(null,b)})},Wc=pc,Nc=function(a){_.oa.call(this,a)};_.r(Nc,_.oa);Nc.prototype.name="cancel";var Kc=function(a,b){this.a=a;this.b=b};
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.Xc=function(a,b){this.l=[];this.F=a;this.w=b||null;this.j=this.c=!1;this.h=void 0;this.I=this.K=this.o=!1;this.m=0;this.a=null;this.D=0};_.Xc.prototype.cancel=function(a){if(this.c)this.h instanceof _.Xc&&this.h.cancel();else{if(this.a){var b=this.a;delete this.a;a?b.cancel(a):(b.D--,0>=b.D&&b.cancel())}this.F?this.F.call(this.w,this):this.I=!0;this.c||this.C(new _.Yc)}};_.Xc.prototype.H=function(a,b){this.o=!1;Zc(this,a,b)};
var Zc=function(a,b,c){a.c=!0;a.h=c;a.j=!b;$c(a)},bd=function(a){if(a.c){if(!a.I)throw new ad;a.I=!1}};_.Xc.prototype.g=function(a){bd(this);Zc(this,!0,a)};_.Xc.prototype.C=function(a){bd(this);Zc(this,!1,a)};_.dd=function(a,b,c){_.cd(a,b,null,c)};_.cd=function(a,b,c,d){a.l.push([b,c,d]);a.c&&$c(a)};_.Xc.prototype.then=function(a,b,c){var d,e,f=new _.Gc(function(a,b){d=a;e=b});_.cd(this,d,function(a){a instanceof _.Yc?f.cancel():e(a)});return f.then(a,b,c)};Dc(_.Xc);
_.Xc.prototype.b=function(a){var b=new _.Xc;_.cd(this,b.g,b.C,b);a&&(b.a=this,this.D++);return b};
var ed=function(a){return(0,_.Ka)(a.l,function(a){return _.ja(a[1])})},$c=function(a){if(a.m&&a.c&&ed(a)){var b=a.m,c=fd[b];c&&(_.k.clearTimeout(c.a),delete fd[b]);a.m=0}a.a&&(a.a.D--,delete a.a);for(var b=a.h,d=c=!1;a.l.length&&!a.o;){var e=a.l.shift(),f=e[0],h=e[1],e=e[2];if(f=a.j?h:f)try{var l=f.call(e||a.w,b);_.p(l)&&(a.j=a.j&&(l==b||l instanceof Error),a.h=b=l);if(Ec(b)||"function"===typeof _.k.Promise&&b instanceof _.k.Promise)d=!0,a.o=!0}catch(n){b=n,a.j=!0,ed(a)||(c=!0)}}a.h=b;d&&(l=(0,_.t)(a.H,
a,!0),d=(0,_.t)(a.H,a,!1),b instanceof _.Xc?(_.cd(b,l,d),b.K=!0):b.then(l,d));c&&(b=new gd(b),fd[b.a]=b,a.m=b.a)},ad=function(){_.oa.call(this)};_.r(ad,_.oa);ad.prototype.message="Deferred has already fired";ad.prototype.name="AlreadyCalledError";_.Yc=function(){_.oa.call(this)};_.r(_.Yc,_.oa);_.Yc.prototype.message="Deferred was canceled";_.Yc.prototype.name="CanceledError";var gd=function(a){this.a=_.k.setTimeout((0,_.t)(this.g,this),0);this.b=a}; gd.prototype.g=function(){delete fd[this.a];throw this.b;};var fd={};
var hd=!_.z||9<=Number(Ab);!_.mb&&!_.z||_.z&&9<=Number(Ab)||_.mb&&_.zb("1.9.1");_.z&&_.zb("9");_.id=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;_.kd=function(){this.a="";this.g=_.jd;this.b=null};_.kd.prototype.mb=!0;_.kd.prototype.La=function(){return this.b};_.kd.prototype.Pa=!0;_.kd.prototype.Ma=function(){return this.a};_.jd={};_.ld=function(a,b){var c=new _.kd;c.a=a;c.b=b;return c};_.ld("<!DOCTYPE html>",0);_.ld("",0);_.md=_.ld("<br>",0);
var sd,vd,ud;_.pd=function(a){return a?new _.nd(_.od(a)):pa||(pa=new _.nd)};_.rd=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=_.qd(window.document,"*",a,b)[0];return d||null};
_.qd=function(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){d=a.getElementsByClassName(c);if(e){a={};for(var f=b=0,h;h=d[f];f++)e==h.nodeName&&(a[b++]=h);a.length=b;return a}return d}d=a.getElementsByTagName(e||"*");if(c){a={};for(f=b=0;h=d[f];f++)e=h.className,"function"==typeof e.split&&_.Na(e.split(/\s+/),c)&&(a[b++]=h);a.length=b;return a}return d};
_.td=function(a,b){_.Va(b,function(b,d){b&&b.Pa&&(b=b.Ma());"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:sd.hasOwnProperty(d)?a.setAttribute(sd[d],b):_.ra(d,"aria-")||_.ra(d,"data-")?a.setAttribute(d,b):a[d]=b})};sd={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
vd=function(a,b,c){function d(c){c&&b.appendChild(_.u(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!_.la(f)||_.ia(f)&&0<f.nodeType?d(f):(0,_.x)(ud(f)?_.Ra(f):f,d)}};_.wd=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.od=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};ud=function(a){if(a&&"number"==typeof a.length){if(_.ia(a))return"function"==typeof a.item||"string"==typeof a.item;if(_.ja(a))return"function"==typeof a.item}return!1};
_.nd=function(a){this.a=a||_.k.document||window.document};_.g=_.nd.prototype;_.g.xa=_.pd;_.g.B=function(a){return _.u(a)?this.a.getElementById(a):a};
_.g.la=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!hd&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',_.Ca(h.name),'"');if(h.type){f.push(' type="',_.Ca(h.type),'"');var l={};_.ab(l,h);delete l.type;h=l}f.push(">");f=f.join("")}f=d.createElement(f);h&&(_.u(h)?f.className=h:_.w(h)?f.className=h.join(" "):_.td(f,h));2<e.length&&vd(d,f,e);return f};_.g.appendChild=function(a,b){a.appendChild(b)}; _.g.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};
_.yd=function(a,b){this.type="undefined"!=typeof _.xd&&a instanceof _.xd?String(a):a;this.b=this.target=b;this.c=!1;this.zb=!0};_.yd.prototype.h=function(){this.c=!0};_.yd.prototype.g=function(){this.zb=!1};var zd=!_.z||9<=Number(Ab),Ad=_.z&&!_.zb("9");!_.nb||_.zb("528");_.mb&&_.zb("1.9b")||_.z&&_.zb("8")||kb&&_.zb("9.5")||_.nb&&_.zb("528");_.mb&&!_.zb("8")||_.z&&_.zb("9");var Bd=function(a,b){_.yd.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.a=this.state=null;if(a){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;(b=a.relatedTarget)?_.mb&&(_.ib(b,"nodeName")||(b=null)):"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=
b;null===d?(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.a=
a;a.defaultPrevented&&this.g()}};_.r(Bd,_.yd);Bd.prototype.h=function(){Bd.A.h.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};Bd.prototype.g=function(){Bd.A.g.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Ad)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var Cd="closure_listenable_"+(1E6*Math.random()|0),Dd=function(a){return!(!a||!a[Cd])},Ed=0;var Fd=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.Oa=e;this.key=++Ed;this.removed=this.Ja=!1},Gd=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.Oa=null};var Hd=function(a){this.src=a;this.a={};this.b=0},Jd=function(a,b,c,d,e,f){var h=b.toString();b=a.a[h];b||(b=a.a[h]=[],a.b++);var l=Id(b,c,e,f);-1<l?(a=b[l],d||(a.Ja=!1)):(a=new Fd(c,a.src,h,!!e,f),a.Ja=d,b.push(a));return a};Hd.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Id(e,b,c,d);return-1<b?(Gd(e[b]),_.Oa(e,b),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var Kd=function(a,b){var c=b.type;c in a.a&&_.Pa(a.a[c],b)&&(Gd(b),0==a.a[c].length&&(delete a.a[c],a.b--))};Hd.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Gd(d[e]);delete this.a[c];this.b--}return b};
var Ld=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Id(a,c,d,e));return-1<b?a[b]:null},Md=function(a){var b=_.p(void 0)?"undefined":void 0,c=_.p(b),d=c?b.toString():"",e=_.p(void 0);return Wa(a.a,function(a){for(var b=0;b<a.length;++b)if(!(c&&a[b].type!=d||e&&void 0!=a[b].capture))return!0;return!1})},Id=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.capture==!!c&&f.Oa==d)return e}return-1};
var Nd,Od,Pd,Sd,Ud,Zd,Vd,ae,$d,Wd,Td,be,Rd;Nd="closure_lm_"+(1E6*Math.random()|0);Od={};Pd=0;_.Qd=function(a,b,c,d,e){if(_.w(b)){for(var f=0;f<b.length;f++)_.Qd(a,b[f],c,d,e);return null}c=Rd(c);return Dd(a)?a.listen(b,c,d,e):Sd(a,b,c,!1,d,e)};
Sd=function(a,b,c,d,e,f){if(!b)throw Error("h");var h=!!e,l=Td(a);l||(a[Nd]=l=new Hd(a));c=Jd(l,b,c,d,e,f);if(c.proxy)return c;d=Ud();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,h);else if(a.attachEvent)a.attachEvent(Vd(b.toString()),d);else throw Error("i");Pd++;return c};Ud=function(){var a=Wd,b=zd?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};
_.Xd=function(a,b,c,d,e){if(_.w(b)){for(var f=0;f<b.length;f++)_.Xd(a,b[f],c,d,e);return null}c=Rd(c);return Dd(a)?a.Na(b,c,d,e):Sd(a,b,c,!0,d,e)};_.Yd=function(a,b,c,d,e){if(_.w(b))for(var f=0;f<b.length;f++)_.Yd(a,b[f],c,d,e);else c=Rd(c),Dd(a)?a.Sa(b,c,d,e):a&&(a=Td(a))&&(b=Ld(a,b,c,!!d,e))&&Zd(b)};
Zd=function(a){if(!_.ka(a)&&a&&!a.removed){var b=a.src;if(Dd(b))Kd(b.g,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent&&b.detachEvent(Vd(c),d);Pd--;(c=Td(b))?(Kd(c,a),0==c.b&&(c.src=null,b[Nd]=null)):Gd(a)}}};Vd=function(a){return a in Od?Od[a]:Od[a]="on"+a};ae=function(a,b,c,d){var e=!0;if(a=Td(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.removed&&(f=$d(f,d),e=e&&!1!==f)}return e};
$d=function(a,b){var c=a.listener,d=a.Oa||a.src;a.Ja&&Zd(a);return c.call(d,b)};
Wd=function(a,b){if(a.removed)return!0;if(!zd){var c=b||_.na("window.event");b=new Bd(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.b;e;e=e.parentNode)c.push(e);a=a.type;for(var f=c.length-1;!b.c&&0<=f;f--)b.b=c[f],e=ae(c[f],a,!0,b),d=d&&e;for(f=0;!b.c&&f<c.length;f++)b.b=c[f],e=ae(c[f],a,!1,b),d=d&&e}return d}return $d(a,new Bd(b,this))}; Td=function(a){a=a[Nd];return a instanceof Hd?a:null};be="__closure_events_fn_"+(1E9*Math.random()>>>0);Rd=function(a){if(_.ja(a))return a;a[be]||(a[be]=function(b){return a.handleEvent(b)});return a[be]};oc(function(a){Wd=a(Wd)});
_.N=function(){_.H.call(this);this.g=new Hd(this);this.ba=this;this.I=null};_.r(_.N,_.H);_.N.prototype[Cd]=!0;_.N.prototype.H=function(a){this.I=a};_.N.prototype.removeEventListener=function(a,b,c,d){_.Yd(this,a,b,c,d)};
_.O=function(a,b){var c,d=a.I;if(d)for(c=[];d;d=d.I)c.push(d);a=a.ba;d=b.type||b;if(_.u(b))b=new _.yd(b,a);else if(b instanceof _.yd)b.target=b.target||a;else{var e=b;b=new _.yd(d,a);_.ab(b,e)}var e=!0;if(c)for(var f=c.length-1;!b.c&&0<=f;f--){var h=b.b=c[f];e=h.na(d,!0,b)&&e}b.c||(h=b.b=a,e=h.na(d,!0,b)&&e,b.c||(e=h.na(d,!1,b)&&e));if(c)for(f=0;!b.c&&f<c.length;f++)h=b.b=c[f],e=h.na(d,!1,b)&&e;return e};_.g=_.N.prototype;
_.g.v=function(){_.N.A.v.call(this);this.g&&this.g.removeAll(void 0);this.I=null};_.g.listen=function(a,b,c,d){return Jd(this.g,String(a),b,!1,c,d)};_.g.Na=function(a,b,c,d){return Jd(this.g,String(a),b,!0,c,d)};_.g.Sa=function(a,b,c,d){return this.g.remove(String(a),b,c,d)}; _.g.na=function(a,b,c){a=this.g.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.capture==b){var h=f.listener,l=f.Oa||f.src;f.Ja&&Kd(this.g,f);d=!1!==h.call(l,c)&&d}}return d&&0!=c.zb};
var ce=function(){};ce.prototype.a=null;var ee=function(a){var b;(b=a.a)||(b={},de(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var fe,ge=function(){};_.r(ge,ce);var he=function(a){return(a=de(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},de=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("j");}return a.b};fe=new ge;
_.ie=function(a,b){_.N.call(this);this.b=a||1;this.a=b||_.k;this.c=(0,_.t)(this.yc,this);this.h=(0,_.m)()};_.r(_.ie,_.N);_.g=_.ie.prototype;_.g.qa=!1;_.g.X=null;_.g.setInterval=function(a){this.b=a;this.X&&this.qa?(this.stop(),this.start()):this.X&&this.stop()};_.g.yc=function(){if(this.qa){var a=(0,_.m)()-this.h;0<a&&a<.8*this.b?this.X=this.a.setTimeout(this.c,this.b-a):(this.X&&(this.a.clearTimeout(this.X),this.X=null),_.O(this,"tick"),this.qa&&(this.X=this.a.setTimeout(this.c,this.b),this.h=(0,_.m)()))}};
_.g.start=function(){this.qa=!0;this.X||(this.X=this.a.setTimeout(this.c,this.b),this.h=(0,_.m)())};_.g.stop=function(){this.qa=!1;this.X&&(this.a.clearTimeout(this.X),this.X=null)};_.g.v=function(){_.ie.A.v.call(this);this.stop();delete this.a};_.je=function(a,b,c){if(_.ja(a))c&&(a=(0,_.t)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.t)(a.handleEvent,a);else throw Error("k");return 2147483647<Number(b)?-1:_.k.setTimeout(a,b||0)};_.ke=function(a){_.k.clearTimeout(a)};
var le=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,me=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?(0,window.decodeURIComponent)(e.replace(/\+/g," ")):"")}}};
var ne=function(a){_.N.call(this);this.headers=new _.L;this.o=a||null;this.b=!1;this.m=this.a=null;this.F="";this.c=this.C=this.h=this.w=!1;this.l=0;this.j=null;this.V="";this.M=this.N=!1},oe,pe,qe,ye,xe,ue,ze;_.r(ne,_.N);oe=/^https?$/i;pe=["POST","PUT"];qe=[];_.re=function(a,b,c,d,e,f,h){var l=new ne;qe.push(l);b&&l.listen("complete",b);l.Na("ready",l.Y);f&&(l.l=Math.max(0,f));h&&(l.N=h);l.send(a,c,d,e)};ne.prototype.Y=function(){this.$();_.Pa(qe,this)};
ne.prototype.send=function(a,b,c,d){if(this.a)throw Error("l`"+this.F+"`"+a);b=b?b.toUpperCase():"GET";this.F=a;this.w=!1;this.b=!0;this.a=this.o?he(this.o):he(fe);this.m=this.o?ee(this.o):ee(fe);this.a.onreadystatechange=(0,_.t)(this.T,this);try{this.C=!0,this.a.open(b,String(a),!0),this.C=!1}catch(f){se(this);return}a=c||"";var e=new _.L(this.headers);d&&_.ic(d,function(a,b){e.set(b,a)});d=_.Ma(e.W(),te);c=_.k.FormData&&a instanceof _.k.FormData;!_.Na(pe,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
e.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.V&&(this.a.responseType=this.V);"withCredentials"in this.a&&this.a.withCredentials!==this.N&&(this.a.withCredentials=this.N);try{ue(this),0<this.l&&((this.M=ve(this.a))?(this.a.timeout=this.l,this.a.ontimeout=(0,_.t)(this.S,this)):this.j=_.je(this.S,this.l,this)),this.h=!0,this.a.send(a),this.h=!1}catch(f){se(this)}};var ve=function(a){return _.z&&_.zb(9)&&_.ka(a.timeout)&&_.p(a.ontimeout)},te=function(a){return"content-type"==a.toLowerCase()};
ne.prototype.S=function(){"undefined"!=typeof _.aa&&this.a&&(_.O(this,"timeout"),this.abort(8))};var se=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);we(a);xe(a)},we=function(a){a.w||(a.w=!0,_.O(a,"complete"),_.O(a,"error"))};ne.prototype.abort=function(){this.a&&this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1,_.O(this,"complete"),_.O(this,"abort"),xe(this))};ne.prototype.v=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),xe(this,!0));ne.A.v.call(this)};
ne.prototype.T=function(){this.G||(this.C||this.h||this.c?ye(this):this.K())};ne.prototype.K=function(){ye(this)};ye=function(a){if(a.b&&"undefined"!=typeof _.aa&&(!a.m[1]||4!=(a.a?a.a.readyState:0)||2!=ze(a)))if(a.h&&4==(a.a?a.a.readyState:0))_.je(a.T,0,a);else if(_.O(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{_.Ae(a)?(_.O(a,"complete"),_.O(a,"success")):we(a)}finally{xe(a)}}};
xe=function(a,b){if(a.a){ue(a);var c=a.a,d=a.m[0]?_.ma:null;a.a=null;a.m=null;b||_.O(a,"ready");try{c.onreadystatechange=d}catch(e){}}};ue=function(a){a.a&&a.M&&(a.a.ontimeout=null);_.ka(a.j)&&(_.ke(a.j),a.j=null)};
_.Ae=function(a){var b=ze(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.F).match(le)[1]||null,!a&&_.k.self&&_.k.self.location&&(a=_.k.self.location.protocol,a=a.substr(0,a.length-1)),b=!oe.test(a?a.toLowerCase():"");c=b}return c};ze=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}};oc(function(a){ne.prototype.K=a(ne.prototype.K)});
var Ce;_.P=function(a){_.H.call(this);this.S=a;this.I={}};_.r(_.P,_.H);var Be=[];_.P.prototype.listen=function(a,b,c,d){_.w(b)||(b&&(Be[0]=b.toString()),b=Be);for(var e=0;e<b.length;e++){var f=_.Qd(a,b[e],c||this.handleEvent,d||!1,this.S||this);if(!f)break;this.I[f.key]=f}return this};_.De=function(a,b,c,d){Ce(a,b,c,d,void 0)};Ce=function(a,b,c,d,e,f){if(_.w(c))for(var h=0;h<c.length;h++)Ce(a,b,c[h],d,e,f);else(b=_.Xd(b,c,d||a.handleEvent,e,f||a.S||a))&&(a.I[b.key]=b)};
_.P.prototype.Sa=function(a,b,c,d,e){if(_.w(b))for(var f=0;f<b.length;f++)this.Sa(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.S||this,c=Rd(c),d=!!d,b=Dd(a)?Ld(a.g,String(b),c,d,e):a?(a=Td(a))?Ld(a,b,c,d,e):null:null,b&&(Zd(b),delete this.I[b.key]);return this};_.P.prototype.removeAll=function(){_.Va(this.I,function(a,b){this.I.hasOwnProperty(b)&&Zd(a)},this);this.I={}};_.P.prototype.v=function(){_.P.A.v.call(this);this.removeAll()};_.P.prototype.handleEvent=function(){throw Error("m");};
_.Ee=function(a){_.B(this,a,0,null,null)};_.r(_.Ee,_.A);var Ge=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("n");return d.replace(/%([0\-\ \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,d,l,n,q,v,M){if("%"==q)return"%";var e=c.shift();if("undefined"==typeof e)throw Error("o");arguments[0]=e;return Fe[q].apply(null,arguments)})},Fe={s:function(a,b,c){return(0,window.isNaN)(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+Da(" ",Number(c)-a.length):Da(" ",Number(c)-a.length)+a},f:function(a,
b,c,d,e){d=a.toString();(0,window.isNaN)(e)||""==e||(d=(0,window.parseFloat)(a).toFixed(e));var f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if((0,window.isNaN)(c)||d.length>=Number(c))return d;d=(0,window.isNaN)(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+Da(" ",a):f+Da(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,f,h,l){return Fe.f((0,window.parseInt)(a,10),b,c, d,0,f,h,l)}};Fe.i=Fe.d;Fe.u=Fe.d;
_.Q=function(a,b){for(var c=[],d=0;d<arguments.length;d++)if(arguments[d]instanceof Error)c.push(arguments[d].stack);else if("object"==typeof arguments[d])try{c.push(JSON.stringify(arguments[d]))}catch(e){c.push("_error_("+e+")")}else c.push(arguments[d]);window.console&&(d=new Date,d=Ge("%02d-%02d ",d.getMonth()+1,d.getDate())+d.toLocaleTimeString(void 0,{hour12:!1})+Ge(".%03d",d.getMilliseconds()),window.console.log(d+" info: "+Ge.apply({},c)))};
_.Ie=function(a){_.B(this,a,"h_exts",He,null)};_.r(_.Ie,_.A);var He=[2];_.Ie.messageId="h_exts";var Je,Ke,Le,Oe,Qe,af,Te,Ve,Ue,Ye,We,Pe,bf;_.R=function(a,b){this.b=this.D=this.h="";this.c=null;this.l=this.a="";this.j=!1;var c;a instanceof _.R?(this.j=_.p(b)?b:a.j,Je(this,a.h),this.D=a.D,this.b=a.b,Ke(this,a.c),this.a=a.a,Le(this,Me(a.g)),_.Ne(this,a.l)):a&&(c=String(a).match(le))?(this.j=!!b,Je(this,c[1]||"",!0),this.D=Oe(c[2]||""),this.b=Oe(c[3]||"",!0),Ke(this,c[4]),this.a=Oe(c[5]||"",!0),Le(this,c[6]||"",!0),_.Ne(this,c[7]||"",!0)):(this.j=!!b,this.g=new Pe(null,0,this.j))};
_.R.prototype.toString=function(){var a=[],b=this.h;b&&a.push(Qe(b,Te,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.D)&&a.push(Qe(b,Te,!0),"@"),a.push((0,window.encodeURIComponent)(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.c,null!=c&&a.push(":",String(c));if(c=this.a)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(Qe(c,"/"==c.charAt(0)?Ue:Ve,!0));(c=this.g.toString())&&a.push("?",c);(c=this.l)&&a.push("#",Qe(c,We));return a.join("")};
Je=function(a,b,c){a.h=c?Oe(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))};Ke=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("r`"+b);a.c=b}else a.c=null};Le=function(a,b,c){b instanceof Pe?(a.g=b,Xe(a.g,a.j)):(c||(b=Qe(b,Ye)),a.g=new Pe(b,0,a.j))};_.S=function(a,b,c){a.g.set(b,c)};_.Ne=function(a,b,c){a.l=c?Oe(b):b};_.Ze=function(a){return a instanceof _.R?new _.R(a):new _.R(a,void 0)};
_.$e=function(a,b){a instanceof _.R||(a=_.Ze(a));b instanceof _.R||(b=_.Ze(b));var c=a;a=new _.R(c);var d=!!b.h;d?Je(a,b.h):d=!!b.D;d?a.D=b.D:d=!!b.b;d?a.b=b.b:d=null!=b.c;var e=b.a;if(d)Ke(a,b.c);else if(d=!!b.a)if("/"!=e.charAt(0)&&(c.b&&!c.a?e="/"+e:(c=a.a.lastIndexOf("/"),-1!=c&&(e=a.a.substr(0,c+1)+e))),".."==e||"."==e)e="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){for(var c=_.ra(e,"/"),e=e.split("/"),f=[],h=0;h<e.length;){var l=e[h++];"."==l?c&&h==e.length&&f.push(""):".."==l?((1<f.length||
1==f.length&&""!=f[0])&&f.pop(),c&&h==e.length&&f.push("")):(f.push(l),c=!0)}e=f.join("/")}d?a.a=e:d=""!==b.g.toString();d?Le(a,Me(b.g)):d=!!b.l;d&&_.Ne(a,b.l);return a};Oe=function(a,b){return a?b?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""};Qe=function(a,b,c){return _.u(a)?(a=(0,window.encodeURI)(a).replace(b,af),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};af=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};
Te=/[#\/\?@]/g;Ve=/[\#\?:]/g;Ue=/[\#\?]/g;Ye=/[\#\?@]/g;We=/#/g;Pe=function(a,b,c){this.b=this.a=null;this.g=a||null;this.c=!!c};bf=function(a){a.a||(a.a=new _.L,a.b=0,a.g&&me(a.g,function(b,c){b=(0,window.decodeURIComponent)(b.replace(/\+/g," "));bf(a);a.g=null;b=cf(a,b);var d=a.a.get(b);d||a.a.set(b,d=[]);d.push(c);a.b+=1}))};Pe.prototype.remove=function(a){bf(this);a=cf(this,a);return _.gc(this.a,a)?(this.g=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};
Pe.prototype.clear=function(){this.a=this.g=null;this.b=0};var df=function(a,b){bf(a);b=cf(a,b);return _.gc(a.a,b)};Pe.prototype.W=function(){bf(this);for(var a=this.a.R(),b=this.a.W(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};Pe.prototype.R=function(a){bf(this);var b=[];if(_.u(a))df(this,a)&&(b=_.Qa(b,this.a.get(cf(this,a))));else{a=this.a.R();for(var c=0;c<a.length;c++)b=_.Qa(b,a[c])}return b};
Pe.prototype.set=function(a,b){bf(this);this.g=null;a=cf(this,a);df(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};Pe.prototype.get=function(a,b){a=a?this.R(a):[];return 0<a.length?String(a[0]):b};_.ef=function(a,b,c){a.remove(b);0<c.length&&(a.g=null,a.a.set(cf(a,b),_.Ra(c)),a.b+=c.length)};
Pe.prototype.toString=function(){if(this.g)return this.g;if(!this.a)return"";for(var a=[],b=this.a.W(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.R(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(h)}return this.g=a.join("&")};
var Me=function(a){var b=new Pe;b.g=a.g;a.a&&(b.a=new _.L(a.a),b.b=a.b);return b},cf=function(a,b){b=String(b);a.c&&(b=b.toLowerCase());return b},Xe=function(a,b){b&&!a.c&&(bf(a),a.g=null,a.a.forEach(function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),_.ef(this,c,a))},a));a.c=b};
var ff;ff=function(a){return(a=a.exec(_.Sa))?a[1]:""};_.gf=function(){if(Cb)return ff(/Firefox\/([0-9.]+)/);if(_.z||lb||kb)return xb;if(Gb)return db()?ff(/CriOS\/([0-9.]+)/):ff(/Chrome\/([0-9.]+)/);if(Hb&&!db())return ff(/Version\/([0-9.]+)/);if(Db||Eb){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.Sa);if(a)return a[1]+"."+a[2]}else if(Fb)return(a=ff(/Android\s+([0-9.]+)/))?a:ff(/Version\/([0-9.]+)/);return""}();
var hf=function(a,b){_.yd.call(this,a,b);this.U=b};_.r(hf,_.yd);var jf=function(a){_.B(this,a,"capi_md1571",null,null)};_.r(jf,_.A);var kf={rb:0,Ec:1,Cc:2,qb:3,eb:4};jf.messageId="capi_md1571";var lf=function(a){_.B(this,a,0,null,null)};_.r(lf,_.A);var nf=function(){for(var a=10,b=mf,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},mf="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";_.of=function(a,b){_.H.call(this);this.j=b||nf();this.c=this.a="";this.b=this.g=null;this.l=a;this.h=new _.P(this);_.K(this,this.h);this.h.listen(window,"message",this.m)};_.r(_.of,_.H);_.of.prototype.ca=function(a,b,c){this.c=a;this.g=b;this.b=c};
_.of.prototype.m=function(a){a=a.a;var b=a.origin;this.g&&this.g!=a.source||"*"!=this.c&&this.c!=b?b=!1:this.b?(b=(new _.R(b)).b,b=_.sa(b,this.b)?b.length==this.b.length||"."==this.b[0]||"."==b[b.length-1-this.b.length]:!1):b=!0;if(b&&(b=a.data)&&_.u(b)&&"["==b[0]){try{var c=JSON.parse(b);if(!_.w(c))return}catch(d){return}if(0!=c.length&&"capi_md1571"==c[0]&&(c=new jf(c),_.C(c,1)==this.j)){b=_.C(c,3);if(!this.a)this.a=b;else if(this.a!=b)return;"*"!=this.c&&this.g||this.ca(a.origin,a.source);1==_.C(c,
2)?this.send(2):this.l(c,a)}}};_.of.prototype.send=function(a,b,c){if(this.a&&this.g){b=b||new jf;_.D(b,3,this.j);_.D(b,1,this.a);_.D(b,2,a);var d=JSON.stringify(_.F(b)),e=this.g,f=this.c;_.z?_.je(function(){e.postMessage(d,f)}):c?e.postMessage(d,f,c):e.postMessage(d,f)}};
var pf=function(a,b,c,d,e){this.g=_.Lc();this.a=new _.of((0,_.t)(this.h,this),d);this.a.ca(a,b,e);this.a.a=c;this.b=new _.ie(50);this.b.start();_.Qd(this.b,"tick",this.c,!1,this);this.c();a=this.g.a;b=this.j;b=Jc(b,b,this);b.g=!0;Sc(a,b)};pf.prototype.j=function(){_.J(this.a);_.Yd(this.b,"tick",this.c,!1,this);_.J(this.b)};pf.prototype.c=function(){this.a.send(1)};pf.prototype.h=function(a,b){2==_.C(a,2)&&this.g.b(b.origin)};
var qf=function(a,b,c){_.H.call(this);this.b=a;a=_.C(b,3);b=_.C(b,1);this.a=new _.of((0,_.t)(this.g,this),b);this.a.a=a;c&&this.a.ca(c.origin,c.source);_.K(this,this.a)};_.r(qf,_.H);qf.prototype.send=function(a){var b=new jf;_.G(b,4,a);this.a.send(kf.rb,b)};qf.prototype.connect=function(a,b){this.a.ca(a,b);this.a.send(kf.qb)};qf.prototype.g=function(a){_.C(a,2)==kf.rb&&(a=_.E(a,lf,4),this.b(a))};qf.prototype.c=_.ma;
var sf=function(a,b,c){_.H.call(this);this.h=a;this.b=this.a=this.g=null;c?(this.b=c.ports[0],rf(this)):(this.a=new _.of(_.ma,_.C(b,1)),a=_.C(b,3),this.a.a=a)};_.r(sf,_.H);sf.prototype.v=function(){sf.A.v.call(this);this.b&&this.b.close();_.J(this.a)};sf.prototype.c=function(){this.g=new _.P(this);_.K(this,this.g);rf(this)};sf.prototype.send=function(a){this.b.postMessage(_.F(a))};
sf.prototype.connect=function(a,b){var c=new window.MessageChannel;this.b=c.port1;rf(this);var d=this.a;this.a=null;c=c.port2;d.ca(a,b);d.send(kf.eb,void 0,[c]);_.J(d)};var rf=function(a){a.b&&a.g&&(a.g.listen(a.b,"message",a.j),a.b.start())};sf.prototype.j=function(a){a=a.a;try{var b=new lf(a.data)}catch(c){return}this.h(b)};
var tf=function(a,b,c){var d=!1;_.p(_.C(b,2))?_.C(b,2)==kf.eb&&(d=!0):d=Gb;return d?new sf(a,b,c):new qf(a,b,c)};var yf,Af;_.uf=function(){_.N.call(this);this.j=null;this.l=!1;this.h=[];this.c=[];_.I(this,this.o,this);this.b=null};_.r(_.uf,_.N);_.uf.prototype.o=function(){for(;this.c.length;)this.c.shift()()};_.wf=function(a){a.o();a.h=[];a.b=new _.Xc;a.c.push((0,_.t)(a.b.cancel,a.b));a.l=!1;_.dd(a.b.b(),function(a){(Md(this.g)||this.I)&&_.vf(this);this.c.push(_.ha(_.J,a))},a)};_.uf.prototype.sendMessage=function(a){xf(this,_.F(a))};var xf=function(a,b){if(a.b){var c=new lf;_.D(c,1,b);_.dd(a.b.b(),function(a){a.send(c)})}};
_.uf.prototype.J=function(){return this};_.uf.prototype.ca=function(a,b,c){this.a.ca(a,b,c)};_.zf=function(a,b,c,d){_.wf(a);yf(a,b,c,d).then(function(a){var d=new jf;_.D(d,1,a.zc);_.D(d,3,c);d=tf((0,_.t)(this.m,this),d);d.connect(a.origin,b);this.b.g(d)},void 0,a)};yf=function(a,b,c,d){var e=nf();b=(new pf("*",b,c,e,d)).g.a;a.c.push((0,_.t)(b.cancel,b));return b.then(function(a){return{zc:e,origin:a}})};
_.uf.prototype.C=function(a,b){if(_.C(a,2)==kf.qb||_.C(a,2)==kf.eb)_.J(this.a),this.a=null,this.b.g(tf((0,_.t)(this.m,this),a,b))};_.uf.prototype.m=function(a){this.h.push(a);this.w()};_.uf.prototype.w=function(){for(;Af(this););};Af=function(a){if(a.G||!a.l||0==a.h.length)return!1;var b=_.C(a.h.shift(),1);a.j&&xf(a.j,b);_.O(a,new hf(b[0],b));return!0};_.vf=function(a){a.l||(a.l=!0,a.b&&_.dd(a.b.b(),function(a){a.c();_.je(this.w,0,this)},a))}; _.uf.prototype.listen=function(a,b,c,d){_.vf(this);return _.uf.A.listen.call(this,a,b,c,d)};_.uf.prototype.Na=function(a,b,c,d){_.vf(this);return _.uf.A.Na.call(this,a,b,c,d)};_.uf.prototype.H=function(a){_.vf(this);return _.uf.A.H.call(this,a)};
var Bf=function(a){this.b=a;this.c="empty";this.a=null;this.g={}};Bf.prototype.setVersion=function(a){this.c=a;return this};Bf.prototype.Qa=function(a){this.a=a;return this};Bf.prototype.pb=function(a){this.g=_.Za(a);return this};var Cf=function(){};var Df=function(){};_.r(Df,Cf);Df.prototype.clear=function(){var a=dc(this.ha(!0)),b=this;(0,_.x)(a,function(a){b.remove(a)})};var Ef=function(a){this.a=a};_.r(Ef,Df);_.g=Ef.prototype;_.g.isAvailable=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};_.g.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};_.g.get=function(a){a=this.a.getItem(a);if(!_.u(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};_.g.remove=function(a){this.a.removeItem(a)};
_.g.ha=function(a){var b=0,c=this.a,d=new ac;d.next=function(){if(b>=c.length)throw $b;var d=c.key(b++);if(a)return d;d=c.getItem(d);if(!_.u(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};_.g.clear=function(){this.a.clear()};_.g.key=function(a){return this.a.key(a)};
var Ff=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a};_.r(Ff,Ef);var Hf=function(a,b){this.g=a;this.a=[];this.b=null;b&&(this.b=new Ff);if(null!=this.b&&this.b.isAvailable()&&(a=this.b.get("__webmonitoring_RateThrottler_history_hourlyRate"),null!=a))try{this.a=Kb(a)||[]}catch(c){}a=!1;_.w(this.a)||(this.a=[],a=!0);for(;this.a.length>this.g;)this.a.shift(),a=!0;a&&Gf(this)},Gf=function(a){if(null!=a.b&&a.b.isAvailable())try{a.b.set("__webmonitoring_RateThrottler_history_hourlyRate",_.Nb(a.a))}catch(b){}};
var If=function(a){_.H.call(this);this.a=a;this.h=!1};_.r(If,_.H);If.prototype.setEnabled=function(a){this.h=a};var T=function(a){If.call(this,a);this.o=100;this.m={};this.O=null;this.g="";this.I=!0;this.j=10;this.b=null;this.c=!1};_.r(T,If);T.prototype.Db=function(a){this.I=a;return this};T.prototype.setUseLocalStorage=T.prototype.Db;T.prototype.xc=function(a){this.j=Math.min(a,100);return this};T.prototype.setMaxErrorsPerHour=T.prototype.xc;T.prototype.Bb=function(a){this.o=a;return this};T.prototype.setGlobalSampling=T.prototype.Bb;T.prototype.tb=function(a,b){this.m[a]=b;return this};
T.prototype.addPerErrorMessageSampling=T.prototype.tb;T.prototype.Ab=function(a){this.O=a;return this};T.prototype.setCallback=T.prototype.Ab;T.prototype.wc=function(a){this.g=a;return this};T.prototype.setClientId=T.prototype.wc;T.prototype.enable=function(){if(this.h)return!1;this.l=window.onerror;window.onerror=this.w.bind(this);this.setEnabled(!0);return!0};T.prototype.enable=T.prototype.enable;
T.prototype.xb=function(a,b,c,d,e){var f=_.Ze(window.location.href);a=null!=e&&null!=e.message?e.message:a;var h;if(h=!_.ja(this.O)||this.O(f.a,a,b,c,d,e))if(h=this.c){h=Object.keys(this.m);for(var l=100,n=0;n<h.length;++n){var q=h[n];(new RegExp(q)).test(a)&&(l=this.m[q])}if(h=(100*Math.random()).toFixed(6)>=this.o*l/100?!1:!0){0<=this.j&&null===this.b&&(this.b=new Hf(this.j,this.I));if(null===this.b)h=0;else{a:{h=this.b;l=(0,_.m)();if(h.a.length==h.g)if(h.a[0]<l-36E5)h.a.shift();else{h=!1;break a}h.a.push(l);
Gf(h);h=!0}h=!h}h=!h&&this.c}}h&&(h=_.Za(this.a.g),h.url=f.a,h.type="JavascriptError",h.error_message=a,l="Other",kb?l="Opera":_.z?l="Internet Explorer":Cb?l="Firefox":Gb?l="Chrome":Hb&&(l="Safari"),h.browser=l,h.browser_version=_.gf,h.os=_.gb()?"Chrome OS":_.y("Linux")?"Linux":_.fb()?"Windows":_.y("Android")?"Android":cb()?"iPhone":_.y("iPad")?"iPad":_.y("iPod")?"iPod":_.eb()?"Mac":"Unknown",l=_.Sa,n="",_.fb()?(n=/Windows (?:NT|Phone) ([0-9.]+)/,n=(l=n.exec(l))?l[1]:"0.0"):db()?(n=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,
n=(l=n.exec(l))&&l[1].replace(/_/g,".")):_.eb()?(n=/Mac OS X ([0-9_.]+)/,n=(l=n.exec(l))?l[1].replace(/_/g,"."):"10"):_.y("Android")?(n=/Android\s+([^\);]+)(\)|;)/,n=(l=n.exec(l))&&l[1]):_.gb()&&(n=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,n=(l=n.exec(l))&&l[1]),h.os_version=n||"",null!=this.a.a&&(h.channel=this.a.a),_.ta(this.g)||(h.guid=this.g),null!=b&&(h.src=b),null!=c&&(h.line=c),null!=d&&(h.column=d),h.prod=this.a.b,h.ver=this.a.c,b=Jf(h),e=null!=e?_.Ea(e.stack):"",_.ta(a)||(c=e.split("\n"),
-1<c[0].indexOf(a)&&(c.splice(0,1),e=c.join("\n"))),Kf(this,"https://clients2.google.com/cr/staging_report",b,e),f={product:this.a.b,url:f.a,js_errors_count:"1"},a=_.Ea(this.a.a),_.ta(a)||(f.version=a),Kf(this,"https://clients2.google.com/cr/staging_perf",Jf(f)))};T.prototype.reportError=T.prototype.xb;T.prototype.w=function(a,b,c,d,e){this.xb(a,b,c,d,e);null!=this.l&&_.ja(this.l)&&this.l(a,b,c,d,e)};
var Jf=function(a){var b="",c;for(c in a)b+=_.ta(b)?"?":"&",b+=c+"="+(0,window.encodeURIComponent)(a[c]);return b},Kf=function(a,b,c,d){d=d||"";var e=_.ta(d)?{}:{"Content-Type":"text/plain"};_.re(b+c,a.H.bind(a,b),"POST",d,e,6E4,!0)};T.prototype.H=function(a,b){_.Ae(b.target)};
var Lf=function(a){If.call(this,a);this.O=null;this.b=0};_.r(Lf,If);Lf.prototype.Ab=function(a){this.O=a;return this};var Mf=[{age:6E4,name:"1m"},{age:15E5,name:"25m"},{age:36E5,name:"1h"},{age:36E6,name:"10h"}];Lf.prototype.enable=function(){if(this.h)return!1;if(window.performance&&window.performance.memory){var a=new _.ie(6E4);_.K(this,a);var b=new _.P(this);_.K(this,b);b.listen(a,"tick",this.g);a.start();this.setEnabled(!0);return!0}return!1};
Lf.prototype.g=function(){this.b+=6E4;for(var a="",b=0;b<Mf.length;++b)if(this.b==Mf[b].age){a=Mf[b].name;break}if(""!=a){var b=Nf.test(_.Sa)?"":"32_bit_",c=window.performance.memory;if(c.totalJSHeapSize&&c.usedJSHeapSize){var a=[{name:"total_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Total JS heap (MB)",value:Math.round(c.totalJSHeapSize/1048576)},{name:"used_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Used JS heap (MB)",value:Math.round(c.usedJSHeapSize/1048576)}],b=_.Ze(window.location.href).a,
c="?product="+(0,window.encodeURIComponent)(this.a.b)+"&url="+(0,window.encodeURIComponent)(b),d=_.Ea(this.a.a);_.ta(d)||(c+="&version="+(0,window.encodeURIComponent)(d));for(d=0;d<a.length;++d)c+="&"+(0,window.encodeURIComponent)(a[d].name)+"="+a[d].value,_.ja(this.O)&&this.O(b,a[d].displayName,a[d].value);_.re("https://clients2.google.com/cr/staging_perf"+c,Of,"POST","",null,6E4,!0)}}};var Of=function(a){_.Ae(a.target)},Nf=/(x86_64|Win64)/;
var Pf=function(a){_.H.call(this);this.b=new Bf(a);this.a={}};_.r(Pf,_.H);_.ga("webmonitoring.Monitoring",Pf);Pf.prototype.setVersion=function(a){this.b.setVersion(a);return this};Pf.prototype.setVersion=Pf.prototype.setVersion;Pf.prototype.Qa=function(a){this.b.Qa(a);return this};Pf.prototype.setChannel=Pf.prototype.Qa;Pf.prototype.pb=function(a){this.b.pb(a);return this};Pf.prototype.setContext=Pf.prototype.pb;Pf.prototype.Ka=function(){null!=this.a[2]||(this.a[2]=new T(this.b));return this.a[2]}; Pf.prototype.createJsErrorsReporter=Pf.prototype.Ka;
var Qf=function(a){Pf.call(this,a)};_.r(Qf,Pf);Qf.prototype.Ka=function(){var a=Qf.A.Ka.call(this);a.c=!0;return a};_.Rf=function(){var a=new Qf("Google_Hangouts_Chrome");a.Qa(window.chrome.runtime.id);a.setVersion(window.chrome.runtime.getManifest().version);null!=a.a[1]||(a.a[1]=new Lf(a.b));a.a[1].enable();a.Ka().Db(!1).Bb(100).tb("Script error.",0).enable()};
}catch(e){_._DumpException(e)}
/* _Module_:host */
try{
var hp=function(a,b){a.j=b;_.I(a,function(){this.j=null},a);_.vf(a)},ip=function(a,b){return a.g.get(b)},jp=function(a){_.B(this,a,"uv_r_hrd",null,null)};_.r(jp,_.A);jp.messageId="uv_r_hrd";
var kp=function(a,b){_.Mc(a,null,b,void 0)},lp=function(a){var b=new _.uf;_.wf(b);b.a=new _.of((0,_.t)(b.C,b),a);b.a.ca("*",void 0,void 0);b.c.push(_.ha(_.J,b.a));return b},mp=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.la(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var h=0;h<f;h++)a[e+h]=d[h]}else a.push(d)}};
var np=function(a){this.a=a;_.z||(delete this.a.lpu,delete this.a.ppu)},op=["cn","tp"],pp=function(a,b){if(_.ja(window.document.postMessage)||_.ja(window.postMessage)||_.z&&window.postMessage)var c=1;else if(_.mb)c=2;else{var d;if(d=_.z){d=!1;try{c=window.opener,window.opener={},d=_.ib(window,"opener"),window.opener=c}catch(e){}}c=d?6:4}d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new np(d)};_.ga("GTalk_IFrameChannelConfig.build",pp);
var qp=function(){},tp=function(a){var b=a.ma,c=function(a){c.A.constructor.call(this,a);var b=this.Z.length;this.a=[];for(var d=0;d<b;++d)this.Z[d].Tc||(this.a[d]=new this.Z[d](a))};_.r(c,b);for(var d=[];a;){if(b=a.ma){b.Z&&mp(d,b.Z);var e=b.prototype,f;for(f in e)if(e.hasOwnProperty(f)&&_.ja(e[f])&&e[f]!==b){var h=!!e[f].Sb,l=rp(f,e,d,h);(h=sp(f,e,l,h))&&(c.prototype[f]=h)}}a=a.A&&a.A.constructor}c.prototype.Z=d;return c},rp=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||
(e.push(f),!d));++f);return e},sp=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.Z[c[0]].prototype[a].apply(this,arguments)}:b[a].Ub?e=function(b){a:{var d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var f=this.a[c[e]];if(f=f?f[a].apply(f,d):this.Z[c[e]].prototype[a].apply(this,d)){d=f;break a}}d=!1}return d}:b[a].Tb?e=function(b){a:{var d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var f=
this.a[c[e]],f=f?f[a].apply(f,d):this.Z[c[e]].prototype[a].apply(this,d);if(null!=f){d=f;break a}}d=void 0}return d}:b[a].jc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var f=this.a[c[e]];f?f[a].apply(f,d):this.Z[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],f=0;f<c.length;++f){var q=this.a[c[f]];e.push(q?q[a].apply(q,d):this.Z[c[f]].prototype[a].apply(this,d))}return e}:d||b[a].Ub||b[a].Tb||b[a].jc? e=null:e=up;return e},up=function(){return[]};qp.prototype.j=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};var vp=function(a){(a?a:function(){}).Sb=!0};
var wp=function(){};_.r(wp,qp);wp.prototype.b=function(a){return a};vp(wp.prototype.b);wp.prototype.g=function(){return!0};vp(wp.prototype.g);var xp=function(a){_.B(this,a,0,null,null)};_.r(xp,_.A);var yp=function(a,b){var c=new xp;_.D(c,1,b);_.D(c,2,a);return c},zp=yp("?",0),Ap=yp("q",1),Bp=yp("<",2),Cp=yp(">",3),Dp=yp("~",4),Ep=yp("s",5),Fp={Dc:zp,Mc:Ap,Gc:Bp,Hc:Cp,Fc:Dp,Oc:Ep};var Gp=function(a){_.B(this,a,"h_cc",null,null)};_.r(Gp,_.A);var Hp=function(a){_.B(this,a,0,null,null)};_.r(Hp,_.A);var Ip=function(a){_.B(this,a,0,null,null)};_.r(Ip,_.A);var Jp=function(a){_.B(this,a,0,null,null)};_.r(Jp,_.A);var Kp=function(a){_.B(this,a,0,null,null)};_.r(Kp,_.A);Gp.messageId="h_cc";var Lp=function(a,b){_.D(a,3,b)},Mp=function(a,b){_.D(a,4,b)},Np=function(a,b){_.D(a,11,b)};
var Op=function(a){_.B(this,a,"ci:ec",null,null)};_.r(Op,_.A);Op.messageId="ci:ec";var Pp=function(a){return this.lb.j(a)};var Qp=function(a){this.a=a||{cookie:""}};_.g=Qp.prototype;_.g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("D`"+a);if(/[;\r\n]/.test(b))throw Error("E`"+b);_.p(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.m)()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
_.g.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(";"),e=0,f;e<d.length;e++){f=(0,_.ua)(d[e]);if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.g.remove=function(a,b,c){var d=_.p(this.get(a));this.set(a,"",0,b,c);return d};_.g.W=function(){return Rp(this).keys};_.g.R=function(){return Rp(this).values};_.g.clear=function(){for(var a=Rp(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])}; var Rp=function(a){a=(a.a.cookie||"").split(";");for(var b=[],c=[],d,e,f=0;f<a.length;f++)e=(0,_.ua)(a[f]),d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
var Sp=function(a,b,c){if(!this.lb){for(var d=this.constructor;d&&!d.ma;)d=d.A&&d.A.constructor;d.ma.wb||(d.ma.wb=tp(d));this.lb=new d.ma.wb(this);this.j||(this.j=Pp)}var e=this.lb.b(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(_.ra(e,"https://talkgadget.google.com/talkgadget/")){var d=(new Qp(window.document)).get("WCSDBG",""),d=d.split(";")[0],d=d.split("|")[0],f=["plus.google.com"],h=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<d.length&&!_.Na(f,d)&&h.test(d)&&(e=_.Ze(e),
e=_.Ze("https://"+d+e.a).toString())}this.g=e;this.c=c||new Op;a.notificationsOnly&&_.D(this.c,1,!0);this.b="0";null!=a.authUser?this.b=a.authUser:(c=ip(new _.R(window.location.href),"authuser"),null!=c&&(this.b=c));this.o=a.clientUrl||"notifierclient";c=ip(_.Ze(this.o),"authuser");null!=c&&(this.b=c);this.Ta=a.propertyName||"Google Talk";this.H=a.cssUrl;this.locale=a.locale;this.l=a.debug;this.Ia=a.userJid;this.Fa=a.uiVersion;this.dc=null!=a.rosterExpanded?a.rosterExpanded:!0;this.ba=a.hostLogMinValue;
this.wa=a.hideChat;this.Wb=a.refresh;this.N=a.hideProfileCard;this.V=a.hideStatusMsgs;this.T=a.hideRosterOptions;this.S=a.hideRecentConversations;this.M=a.hideOTR;this.jb=a.hostServerMessageCallback||!1;this.ga=a.isCentralRoster;this.Vb=a.isFullFrame||!1;this.bc=a.rosterClass||"talk_roster";this.ec=a.rosterId||"talk_roster";this.a="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.a=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.va=a.parentToken;
this.ac=b||!1;this.h=_.p(a.isRtl)?a.isRtl:_.id.test(this.locale);this.position=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var l in Fp)b.push(_.F(Fp[l]))}this.C=a.entityId;this.Ga=a.useQuasarPanels||!1;this.Da=a.silent||!1;this.kb=a.ignoreCentralRoster||!1;this.Yb=a.lazy||!1;this.gb=a.handleProfileLinks||!1;this.Y=a.hostSettings;this.m=a.screen;this.w=a.docsConfig;this.Xb=a.jsmode;this.ua=a.moleWidth;this.ta=a.moleHeight;this.sa=a.minimizedMoleHeight||36;this.fc=a.derp;this.Ea=window.location.protocol+
"//"+window.location.host;this.D="";this.K=a.optOutAllowed;this.F=a.legacyTalkSignedIn;this.Ha=a.useSpareMole;this.I=a.conversationId};wp.A||_.r(wp,qp);Sp.ma=wp;
var Up=function(a){var b={},c=_.Ub(a,1,"hangouts.google.com"),d="";0>c.indexOf("://")&&(d="https://",0<=c.indexOf(":")&&23!=_.C(a,2)&&27!=_.C(a,2)&&(d="http://"));-1!=c.indexOf("talkgadget.")?(b.clientBaseUrl=d+c+"/talkgadget/_/",b.clientUrl="chat"):(b.clientBaseUrl=d+c+"/webchat/u/"+_.Ub(a,8,"0")+"/",b.clientUrl="load");b.authUser=_.Ub(a,8,"0");b.propertyName=Tp(_.C(a,2));b.locale=_.C(a,4);b.hideProfileCard=!0;b.parentToken=_.C(a,3);b.isRtl=_.Ub(a,6,!1);b.lazy=_.Ub(a,7,!1);b.entityId=_.C(a,9);b.hostSettings=
_.C(a,5);b.jsmode=_.C(a,11);b.isFullFrame=_.Ub(a,13,!1);b.rosterId=_.Ub(a,12,"talk_roster");b.rosterIframeIdB=_.Ub(a,15,"gtn-roster-iframe-id-b");b.derp=!!_.Ub(a,16,!1);c=_.E(a,Kp,14);null!=c&&(b.isCentralRoster=_.Ub(c,1,!1),b.useQuasarPanels=_.Ub(c,2,!1));c=_.E(a,Hp,10);null!=c&&(b.moleManagerLeftMargin=_.C(c,1),b.moleManagerMiddleMargin=_.C(c,2),b.moleManagerRightMargin=_.C(c,3),b.moleManagerNoMoleAreaMargin=_.C(c,4),b.moleManagerBoundingElementId=_.C(c,5),b.moleWidth=_.C(c,6),b.moleHeight=_.C(c,
7),b.minimizedMoleHeight=_.C(c,8));c=_.E(a,Ip,18);null!=c&&(b.optOutAllowed=_.Ub(c,1,!0),d=_.E(c,Jp,3),null!=d&&(b.legacyTalkSignedIn=_.Ub(d,1,!0)),c=_.C(c,4),null!=c&&(b.useSpareMole=c));b.uiVersion=2;b.hideStatusMsgs=!0;b.hideRecentConversations=!0;c=new Op;_.D(c,2,!0);_.D(c,1,!0);_.D(c,3,!1);b.endpointConfig=c;b.ignoreAutomatedRoster=_.Ub(a,17,!1);b.conversationId=_.C(a,19);return b},Tp=function(a){switch(a){case 1:return"homepage";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";
case 6:return"customersupport";case 9:return"present";case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp";case 36:return"StartPage"}},Vp=function(a,b){if(-1!=a.indexOf("talkgadget.")){var c=_.Ze(a),d=c.a;if(0<=d.indexOf("/u/"))return a;a=d.lastIndexOf("_/");if(0>a||a!=d.length-2)d+="_/";c.a="/u/"+b+d;return c.toString()}return a};
var Wp=function(a,b,c,d,e){_.H.call(this);this.a=a;this.b=d||window.document;this.g=new _.P(this);_.K(this,this.g);var f=_.Sa;d=new _.R(a.g+a.o);_.Ub(a.c,2,!1)||(_.S(d,"ts","0"),_.S(d,"re",a.dc),_.S(d,"ref",a.Wb));_.S(d,"client","sm");_.S(d,"prop",a.Ta);_.S(d,"nav","true");_.S(d,"fid",a.a);a.l&&_.S(d,"debug",a.l);_.S(d,"os",_.pb);_.S(d,"stime",c);a.wa&&_.S(d,"hc",a.wa);for(c=0;c<op.length;++c);b=_.Nb(b.a);_.S(d,"xpc",b);_.S(d,"ec",_.Nb(_.F(a.c)));a.m&&_.S(d,"screen",a.m);-1!=f.indexOf("MSIE")&&_.S(d,
"ua",f);a.va&&_.S(d,"pvt",a.va);a.jb&&_.S(d,"hsmc","true");_.p(a.ba)&&_.S(d,"logl",a.ba);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),_.S(d,"href",b.join("?")));b=new _.R(window.location.href);"false"==ip(b,"uacheck")&&_.S(d,"uacheck",!1);(f=a.Xb)&&_.S(d,"jsmode",f);(f=ip(b,"cssmode"))&&_.S(d,"cssmode",f);(f=ip(b,"convid"))&&_.S(d,"convid",f);if(f=b.g.R("convp"))_.w(f)||(f=[String(f)]),_.ef(d.g,"convp",f);(f=ip(b,"smexp"))&&_.S(d,
"smexp",f);f=b.g.R("mods");a.Yb&&f.push("lazy");e&&(f=_.Qa(f,e));0<f.length&&_.S(d,"mods",f.join(","));if(!a.g||0>a.g.indexOf("/u/"))(e=ip(b,"authuser"))?_.S(d,"authuser",e):null!=a.b&&_.S(d,"authuser",a.b);e=ip(b,"eid");_.ta(_.Ea(e))||_.S(d,"eid",e);_.ta(_.Ea(this.a.C))||_.S(d,"eid",this.a.C);null!=this.a.position&&_.S(d,"pos",this.a.position);_.p(a.Fa)&&_.S(d,"uiv",this.a.Fa);a.H&&_.S(d,"css",a.H);e=a.locale||ip(b,"hl");null!=e&&_.S(d,"hl",e);_.p(a.Ia)&&_.S(d,"uj",a.Ia);null!=a.N&&_.S(d,"hpc",a.N);
null!=a.V&&_.S(d,"hsm",a.V);null!=a.T&&_.S(d,"hro",a.T);null!=a.S&&_.S(d,"hrc",a.S);null!=a.M&&_.S(d,"hotr",a.M);null!=a.ga&&_.S(d,"pop",a.ga);a.ac&&_.S(d,"pal","1");null!=a.Ga&&_.S(d,"uqp",a.Ga);null!=a.K&&_.S(d,"gooa",a.K);null!=a.F&&_.S(d,"gltsi",a.F);null!=a.Ha&&_.S(d,"gusm",a.Ha);null!=a.Da&&_.S(d,"sl",a.Da);a.kb&&_.S(d,"icr","1");a.gb&&_.S(d,"hpl","1");a.Y&&_.S(d,"hs",a.Y);a.w&&_.S(d,"dc",_.Nb(_.F(a.w)));null!=a.ua&&_.S(d,"molew",a.ua);null!=a.ta&&_.S(d,"moleh",a.ta);null!=a.sa&&_.S(d,"mmoleh",
a.sa);a.fc&&_.S(d,"derp","1");a.D&&_.S(d,"fcho",a.D);null!=a.Ea&&_.S(d,"two",a.Ea);null!=a.I&&_.S(d,"convid",a.I);_.S(d,"host","1");_.S(d,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.m)()).toString(36));this.c=d.toString()};_.r(Wp,_.H);
var Xp=function(a,b,c,d){var e=a.b.getElementById(b);e||(e=a.b.createElement("div"),e.id=b,e.className=a.a.bc,a.b.body.appendChild(e));a=(0,_.t)(function(){var a="";this.a.Vb||(a="height:400px");var b=this.b.createElement("iframe");_.td(b,{id:this.a.a,name:this.a.a,"class":"talk_iframe",frameborder:"0",style:a,"aria-hidden":"true"});_.rd("talk_loading_msg",e)||_.wd(e);e.appendChild(b);var l=this.b.getElementById(this.a.a);_.De(this.g,l,["load","error"],function(a){l.contentWindow.postMessage("AllowFrame: Chat", "*");d(a)});l.src=this.c.toString();c()},a);window.setTimeout(a,0)};
var Yp=function(a){var b=_.$e(_.C(a,2),"/webchat/extension-start");_.C(a,5)&&_.S(b,"e",_.C(a,5));return new _.Gc(function(a,d){_.re(b,function(b){_.Ae(b.target)||d();try{var c=b.target;try{var e=c.a?c.a.responseText:""}catch(n){e=""}var l=JSON.parse(e);a(new _.Ie(l))}catch(n){d(n.message)}})})};
var $p=function(){var a=this;_.P.call(this);_.Q("Starting ...");this.listen(window,"unload",this.$);this.b=new _.Ee(JSON.parse((0,window.decodeURI)(window.location.hash.substr(1))));this.a=lp(_.C(this.b,1));_.K(this,this.a);this.g=new _.uf;_.K(this,this.g);kp(Yp(this.b).then(function(b){return Zp(a,b)}),function(a){_.Q("Failed to start : %s.",a||"")})},aq;_.r($p,_.P);
var Zp=function(a,b){if(!a.G&&(a.a.sendMessage(b),_.C(b,1))){var c=new Gp,d=_.Ze(_.C(a.b,2)),e=d.b;null!=d.c&&(e+=":"+d.c);_.D(c,1,e);_.D(c,2,27);_.D(c,13,!0);_.D(c,17,!0);Lp(c,_.C(b,1));Np(c,_.C(a.b,4));Mp(c,_.C(a.b,3)||"en");b=Up(c);var f=new Sp(b,!0,b.endpointConfig);f.g=Vp(f.g,f.b);f.D=window.location.origin;b=pp(f.g,f.a);b=new Wp(f,b,(0,_.m)(),window.document);_.K(a,b);Xp(b,f.ec,function(){},function(){_.zf(a.g,window.document.getElementById(f.a).contentWindow,"31ACFC0_","google.com");hp(a.g, a.a);hp(a.a,a.g);a.a.sendMessage(new jp)})}};_.ga("default_host._DumpException",function(a){return window.console.error(a.stack)});_.Rf();if(!aq||aq.G)aq=new $p;

}catch(e){_._DumpException(e)}
/* _GlobalSuffix_ */
}).call(this,this.default_host);
// Google Inc.
